### ISSUE TITLE
Kaspa WASM: recursive use of an object detected which would lead to unsafe aliasing in rust

### ISSUE THREAD

**Issue by coinchimp** [coinchimp/kaspool-payment#1]
Happening when transaction is submitted:
```ts
    for (const transaction of transactions) {
      if (DEBUG) this.monitoring.debug(`TrxManager: Payment with ransaction ID: ${transaction.id} to be signed`);
      await transaction.sign([this.privateKey]);
      if (DEBUG) this.monitoring.debug(`TrxManager: Payment with ransaction ID: ${transaction.id} to be submitted`);
      await transaction.submit(this.processor.rpc);
      if (DEBUG) this.monitoring.debug(`TrxManager: Payment with ransaction ID: ${transaction.id} submitted`);
      await new Promise(resolve => setTimeout(resolve, 5000)); // 5-second delay
    }
``` 

this is the error:
```
8-Aug-2024 12:00:05 DEBUG TrxManager: Payment with ransaction ID: 0fdf3d90382cc7d87f84aa69fceaa1d9b6f7be0c9ae1be65dac32a3b7a551f3e submitted
8-Aug-2024 12:00:10 DEBUG TrxManager: Payment with ransaction ID: 65d49fe897930ab5e071ee55cfa9ff9e670caa95e541876303b8533643bc7b40 to be signed
8-Aug-2024 12:00:10 DEBUG TrxManager: Payment with ransaction ID: 65d49fe897930ab5e071ee55cfa9ff9e670caa95e541876303b8533643bc7b40 to be submitted
13532 |     getInt32Memory0()[arg0 / 4 + 1] = len1;
13533 |     getInt32Memory0()[arg0 / 4 + 0] = ptr1;
13534 | };
13535 | 
13536 | module.exports.__wbindgen_throw = function(arg0, arg1) {
13537 |     throw new Error(getStringFromWasm0(arg0, arg1));
                  ^
error: recursive use of an object detected which would lead to unsafe aliasing in rust
      at /app/wasm/kaspa/kaspa.js:13537:11
      at <?>.wasm-function[6944]
      at <?>.wasm-function[6946]
      at <?>.wasm-function[4837]
      at /app/wasm/kaspa/kaspa.js:7104:44

Bun v1.1.22-canary.83+1aa35089d (Linux x64)
```

**Comment by coinchimp** [comment]
I got a new [WASM.zip](https://github.com/aspectron/rusty-kaspa/actions/runs/10307671650) from [aspect](https://github.com/aspectron)  and it's working so far. Issue also reported at https://github.com/kaspanet/rusty-kaspa/issues/516

**Comment by coinchimp** [comment]
After many tests, the fix seems to be working fine.
